[package]
name = "tenet-runner"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
serde.workspace = true
sha2.workspace = true
tenet-application.workspace = true
tenet-domain.workspace = true
tenet-kernel.workspace = true

[dev-dependencies]
tempfile.workspace = true
